name: Fly Deploy
on:
  workflow_run:
    workflows: ["Docker Build/Push"]
    types:
      - completed
    branches:
      - main
      - 'releases/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy app
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"