name: Fly Deploy
on:
  workflow_run:
    workflows: ["Docker Build/Push"]
    types:
      - completed
    branches:
      - main
      - 'releases/**'
env:
  IMAGE_NAME: ${{ github.repository }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Pull and deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy app
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --verbose"